<?php
/**
 * Implements hook_wysiwyg_plugin().
 */
function cketawembed_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'ckeditor':
      return array(
        'TAWEmbed' => array(
          'path' => drupal_get_path('module', 'cketawembed') . '/plugin/tawembed',
          'buttons' => array(
            'TAWEmbed' => t('Embedded Action Widget'),
          ),
          'load' => TRUE,
          'internal' => FALSE,
        ),
      );
     break;
  }
}
