<?php

/*
 * implements hook_FORMID_alter()
 *
 * we are limiting the types of nodes that can be embed and also
 * telling the user that.
 */
function takepart_custom_form_embeddable_embed_form_alter(&$form, &$form_state) {
  if(isset($form['wrapper']['nid'])) {
    $form['wrapper']['nid']['#autocomplete_path'] = 'entity-autocomplete/bundle/node/action+video+video_playlist+openpublish_photo_gallery';
    $form['wrapper']['nid']['#description'] = 'Limited to Videos, Playlists, Galleries and Actions';
    $form['wrapper']['view_mode']['#default_value'] = 'embed';
  }
}

/*
 * implements hook_info_alter()
 *
 * we are adding a embed view mode
 */
function takepart_custom_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['embed'] = array('label' => 'Embedded', 'custom settings' => FALSE);
}

function takepart_custom_block_info() {

  return array(
    'page_title_h1' => array(
      'info' => t('Page Title in H1'),
    ),
    'slideshow_controls' => array(
      'info' => t('SlideShow Controls'),
    ),
    'gallery_embed' => array(
      'info' => t('Gallery Embed'),
    ),
  );
}

function takepart_custom_block_view($delta='page_title') {
  switch($delta) {
    case 'slideshow_controls':
      $block['content'] = "<div id='ss_controls'></div>";
      drupal_add_js(drupal_get_path("module", "takepart_custom") ."/takepart_custom.ss_controls.js", array("scope"=>"footer"));
    break;
    case 'gallery_embed':
     $view = views_get_view('photo_gallery');
     $embed = $view->preview('block_2');
     $block['content'] = "embed : <input value ='$embed'>";

    break;
    default :
      $block['content'] = '<h1 class="title"><span>' . drupal_get_title() . '</span></h1>';
  }
  return $block;
}

/**
 * Implements hook_form_alter().
 */
function takepart_custom_form_node_form_alter(&$form, $form_state, $form_id) {
    drupal_add_css(drupal_get_path("module", 'takepart_custom') . "/takepart_custom.css");
    // Add access to the 'Publishing options' fieldset.
    $form['options']['promote']['#access'] = FALSE;
    $form['options']['sticky']['#access'] = FALSE;
    $form['revision_information']['revision']['#default_value'] = 1;
    $form['revision_information']['revision']['#access'] = FALSE;
}

function takepart_custom_wysiwyg_editor_settings_alter(&$settings, &$context) {
  drupal_add_js(drupal_get_path("module", 'takepart_custom') ."/takepart_custom.js");
}

function takepart_custom_omniture_variables() {
  if (current_path() === variable_get('static_404', FALSE)) {
    $variables['s.pageType'] = 'errorPage';
    return array('variables' => $variables);
  }
}
