<?php
/**
 * @file
 * Code for the TakePart Action feature.
 */

include_once('takepart_action.features.inc');

function takepart_action_form_action_node_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_css(
    ".field-name-field-action-sponsor.field-widget-node-reference-autocomplete input.form-autocomplete {width:90%!important;}",
    array('type' => 'inline')
  );
}


function takepart_action_preprocess_page(&$variables) {
   
  if(!empty($variables['node']) && $variables['node']->type == 'action') {
    
    // add the action url as a variable
    $node = $variables['node'];
    $action_url = NULL;
    
    if (!empty($node->field_action_url)) {
      $action_url = $node->field_action_url[$node->language][0]['url'];
    }
    $actionClick_vars = array();
    
    if (valid_url($action_url)) {
      $variables['action_url'] = $node->field_action_url[$node->language][0]['url'];
      $actionClick_vars = array('action_url' => $action_url);
    }
    
    drupal_add_js(array('TPactionClick' => $actionClick_vars), 'setting');

    $path = drupal_get_path('module', 'takepart_action');
    drupal_add_js($path . '/js/takepart-action.js');
  }
  
}