<?php
/**
 * @file
 * Module for embedding nodes a inline collapsible actions.
 */

/**
 * Implements hook_entity_info_alter().
 */
function embedaction_entity_info_alter(&$entity_info) {
  // Add an embedded view mode for nodes.
  $entity_info['node']['view modes']['embedaction'] = array(
    'label' => t('Embedded Petition/Pledge (Collapsed)'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['embedaction_expanded'] = array(
    'label' => t('Embedded Petition/Pledge (Expanded)'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_node_view_alter().
 */
function embedaction_node_view_alter(&$build) {
  // Only the view mode provided by this module should be altered.
  if ($build['#view_mode'] == 'embedaction' || $build['#view_mode'] == 'embedaction_expanded') {
    if (!isset($build['#post_render'])) {
      $build['#post_render'] = array();
    }
    $build['#post_render'][] = 'embedaction_wrap_node';
  }
}

/**
 * Post render callback to wrap a node in a collapsible action wrapper.
 */
function embedaction_wrap_node($markup, $element) {
  $node = $element['#node'];

  $js_path = drupal_get_path('module', 'embedaction') . '/js/embedaction.js';
  drupal_add_js($js_path, array('group' => JS_DEFAULT, 'type' => 'file'));

  $display = array('label' => 'hidden');
  $content = field_view_field('node', $node, 'field_promo_headline', $display);
  $title = render($content);

  $id = 'embedaction-wrapper-' . $node->nid;
  $state = $element['#view_mode'] == 'embedaction_expanded'
    ? 'expanded' : 'collapsed';
  $classes = "{$state} embedaction-wrapper clearfix";

  $pieces = array(
    '<div id="' . $id . '" class="' . $classes . '">',
    '<table class="embedaction-header clearfix"><tbody><tr>',
    '<td class="graphic"><div class="embedaction-button"></div></td>',
    '<td class="title">' . $title . '</td>',
    '</tr></tbody></table>',
    '<div class="embedaction-content clearfix">',
    '<h2 class="embedaction-divider">',
    '<a href="#"><span>[x]</span></a>',
    '</h2>',
    $markup,
    '</div>',
    '</div>',
  );

  return implode('', $pieces);
}
