<?php
/**
 * @file
 * TakePart MegaMenu for the new TP4 theme.
 */

/**
 * Implements hook_help().
 */
function tp_megamenu_help($path, $arg) {
	switch ($path) {
		case 'admin/help#tp_megamenu':
			return '<p>' . t('The new MegaMenu for the TP4 theme') . '</p>';		
	}
}

/**
 * Hook Black Info
 */
function tp_megamenu_block_info(){
  $blocks = array();
  $blocks['tp_megamenu_megamenu'] = array(
    'info' => t('MegaMenu for the TP4 theme'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function tp_megamenu_block_view($delta = ''){
  $block = array();
  switch($delta){
    case 'tp_megamenu_megamenu':
      $block['content'] = tp_megamenu_megamenu();
    break;
  }
  return $block;
}

/*
 *Implements hook_theme()
 */
function tp_megamenu_theme(){
  return array(
    'tp_megamenu_slimnav' => array(
      'arguments' => array(),
      'template' => 'tp-slimnav'
    ),
  );
}

function tp_megamenu_megamenu(){
  /* render parent menu (In the News, Lifestyle, Featured & Columns, etc) */
  $mega_tree = menu_tree_all_data('menu-megamenu', $link = NULL, $max_depth = 1);
  menu_tree_add_active_path($mega_tree);
  $parent_menu = drupal_render(menu_tree_output($mega_tree));
  
  /* render child block) */
  $mega_tree = menu_tree_all_data('menu-megamenu', $link = NULL, $max_depth = 2);
  $output = '';
  $output .= '<ul>';
  foreach($mega_tree as $key => $link){
    $output .= '<li class="mega-item '. $link['link']['mlid']. '">';
    $path = drupal_get_path_alias($mega_tree[$key]['link']['link_path']);
    $output .= '<div class="title">'. l($mega_tree[$key]['link']['link_title'], $path, array('attributes' => array('class' => array($link['link']['options']['attributes']['class'][0])))). '</div>';
    $output .= '<div class="mega-content">';
    //left menu curation
    $menu = render(menu_tree_output($mega_tree[$key]['below']));
    $output .= '<div class="side-menu">';
    if($link['link']['options']['attributes']['title']){
      $output .= '<div class="text">'. $link['link']['options']['attributes']['title']. '</div>';
    }
    $output .= $menu;
    $output .= '</div>';


    //middle content curation
    $url = current(explode("/", $link['link']['href']));
    if($url != 'taxonomy' && $url != 'node'){
      $url = drupal_lookup_path("source", $link['link']['href']);
      $url = current(explode("/", $url));
    }
    if($url == 'taxonomy'){
      $entities = menu_get_object('taxonomy_term', 2, $link['link']['href']);
    }
    elseif($url == 'node'){
      $entities = menu_get_object('node', 1, $link['link']['href']);
    }
    else{
      // url is not a node or taxonomy
    }
    $output .= '<div class="categories">';
    if(isset($entities->field_promo_content['und']) && isset($url)){  
      foreach($entities->field_promo_content['und'] as $key => $entity){
        $node = node_load($entity['target_id']);
        $node_path = drupal_get_path_alias('node/'. $node->nid);
        $thumb = file_load($node->field_thumbnail['und'][0]['fid']);
        $thumb = '<img src="'. image_style_url('homepage_featured_image', $thumb->uri). '">';

        //Subcategory content menu item is linked to a taxonomy term
        if($url == 'taxonomy'){
          $term = $node->field_topic['und'][0]['tid'];
          $term = taxonomy_term_load($term);
          //Subcategory content for menu items with the ID of 'series' (example: Features & Columns)
          if(isset($link['link']['options']['attributes']['id']) && $link['link']['options']['attributes']['id'] == 'series'){
            $author_node = node_load($node->field_author['und'][0]['nid']);
            $series_term = taxonomy_term_load($node->field_series['und'][0]['tid']);
            $text = '<div class="author">'. $author_node->title. '</div>'. l($node->field_promo_headline['und'][0]['value'], $node_path);  //author and promo_headline
            $label = $series_term->name; //TODO: change to Series Name
            $label_path = drupal_get_path_alias('taxonomy/term/'. $series_term->tid);
          }
          else{
            $text = l($node->field_promo_headline['und'][0]['value'], $node_path);
            $label = $term->name;
            $label_path = drupal_get_path_alias('taxonomy/term/'. $term->tid);
          }
        }
        //Subcategory content menu item is linked to a node
        else{
          $label = $node->title;
          $label_path = drupal_get_path_alias('node/'. $node->nid);
          $text = l($node->field_promo_headline['und'][0]['value'], $node_path);
        }
        
        //Output subcategories based on input from menu link ID field
        $output .= '<div class="sub-category">';
        $output .= '<div class="thumb">'. l($thumb, $node_path, array('html' => true)). '</div>';
        $output .= '<div class="label">'. l($label, $label_path). '</div>';
        $output .= '<div class="text">'. $text. '</div>';
        $output .= '</div>'; //end .sub-category

      }
      $output .= '</div>'; //end .categories
      //return more link
      if(isset($link['link']['options']['attributes']['name'])){
        $output .= l($link['link']['options']['attributes']['name'], $path, array('attributes' => array('class' => array('more'))));
      }
      else{
        $output .= l('See More '. $link['link']['link_title'], $path, array('attributes' => array('class' => array('more'))));
      }
    }
    $output .= '</div>'; //end .mega-content
    $output .= '</li>'; //end .mega-item
  }
  $output .= '</ul>';

  return $output;
}

