<?php
/**
 * Implementation of hook_perms()
 */
function takepart_newsletter_signup_view_perm() {
  return array('administer newsletter email collector service');
}


/**
 * Implementation of hook_menu().
 */
function takepart_newsletter_signup_view_menu() {
  $items = array();
    
  $items['admin/settings/takepart-newsletter-signup-service/list'] = array(
  'type' => MENU_NORMAL_ITEM,
	'title' => t('View Records'),
	'description' => t('View Results for TakePart Newsletter Signup'),
	'page callback' => 'takepart_newsletter_signup_view_results_page',
	'page arguments' => array(4),
	'access arguments' => array('administer newsletter email collector service'),
  );
      
  return $items;
}


/**
 * Returns html for page after a user successfully unsubscribes
 */
function takepart_newsletter_signup_view_results_page() {
$string = 'administer newsletter email collector service';
if(user_access($string, $account = NULL, $reset = FALSE)) {
    $email = $_GET['e'];
    $pass = $_GET['p'];
    $delete = $_GET['d'];
    $datefmt = '%m-%e-%Y %T';
    if($delete) {
      $sql = db_query("DELETE from {tp_newsletter_signups} WHERE tns_id = %d",$delete);
      db_result($sql);
    }
    if($email == 'showall' AND $pass == 'picot36atom') {
      $sql = "SELECT 
              tns_id, 
              mail, 
              campaign_id, 
              uid, 
              status, 
              source, 
              if(subscribe_date > 0, FROM_UNIXTIME(subscribe_date, '" . $datefmt . "'),'NA') AS sub_date,
              if(unsubscribe_date > 0, FROM_UNIXTIME(unsubscribe_date, '" . $datefmt . "'), 'NA') AS unsub_date
              FROM {tp_newsletter_signups}";
    } else {
      $sql = 
              "SELECT 
              tns_id, 
              mail, 
              campaign_id, 
              uid, 
              status, 
              source, 
              if(subscribe_date > 0, FROM_UNIXTIME(subscribe_date, '" . $datefmt . "'),'NA') AS sub_date,
              if(unsubscribe_date > 0, FROM_UNIXTIME(unsubscribe_date, '" . $datefmt . "'), 'NA') AS unsub_date
              FROM {tp_newsletter_signups}
              WHERE mail = '" . $email . "'";
    }
    $limit = 50;
    $header = array(
      array('data' => t('TNS ID'), 'field' => 'tns_id'),
      array('data' => t('Email'), 'field' => 'mail', 'sort' => 'asc'),
      array('data' => t('Campaign ID'), 'field' => 'campaign_id'),
      array('data' => t('User ID'), 'field' => 'uid'),
      array('data' => t('Status'), 'field' => 'status'),
      array('data' => t('Source'), 'source' => 'source'),
      array('data' => t('Subscribe Date'), 'subscribe_date' => 'subscribe_date'),
      array('data' => t('Unsubscribe Date'), 'unsubscribe_date' => 'unsubscribe_date'),
     );
     $tablesort = tablesort_sql($header);
     $result    = pager_query($sql . $tablesort, $limit);
     $rows = array();
     while($listing = db_fetch_array($result)) {
       $rows[] = array($listing['tns_id'], $listing['mail'], $listing['campaign_id'], $listing['uid'], $listing['status'], $listing['source'], $listing['sub_date'], $listing['unsub_date']);
    }
    if (!$rows) {
      $rows[] = array(array('data' => t('No subscriptions to display.'), 'colspan' => 8));
    }
     
    $caption     = '';
    $attributes  = array('class="sticky-enabled"');
    $output     .= theme('pager', NULL, $limit, 0);
    $output     .= theme('table', $header, $rows, $attributes = array(), $caption = NULL);
    $output     .= theme('pager', NULL, $limit, 0);
  } else {
    $output = 'Access Denied';
  }
  return $output;
}