<?php

/*
 * implements of hook_block_info()
 */
function context_related_menu_block_info() {
  $blocks['context_related_menu'] = array(
    'info' => 'Context Related Menu',
  );
  return $blocks;
}

/*
 * implements of hook_block_view()
 *
 * if our block is empty we want to still have it show so we can add stuff to it
 * TODO: I think this should be based on somekind of perm and if so maybe should be general
 * for all menu blocks
 */
function context_related_menu_block_view($delta = 'context_menu') {
  $block = menu_block_view($delta);
  // if we have no items we want to show the block so we can add new things
  if (!$block['content']) {
    $block['content']['#markup'] = "empty";
    $block['content']['#contextual_links'] = array("menu" => array("admin/structure/menu/manage", array($delta)));
  }
  return $block;
}

/* 
 * implements hook_context_load_alter()
 *
 * when the context loads we insure we have a menu with the same name as the context
 * and then change the delta to that.
 * If the menu has data we change the module as well
 */
function context_related_menu_context_load_alter(&$context) {
  if(isset($context->reactions['block']['blocks']['context_related_menu-context_related_menu'])) {
    $menu_name = $context->name;
    $menu = menu_load($menu_name);
    if (!$menu) {
      $title = $context->description ? $context->description : $menu_name;
      $menu = array("menu_name" => $menu_name, "title"=> $title, "description" => "");
      //menu_save($menu);
    }
    $context->reactions['block']['blocks']['context_related_menu-context_related_menu']['delta'] = $menu_name;
    if(menu_tree($menu_name)) {
      $context->reactions['block']['blocks']['context_related_menu-context_related_menu']['module'] = 'menu';
    }
    
  }
}
