<?php
  

/**
 * Implement hook_menu().
 */
function slurp_menu() {
  $items = array();
  $items['slurp'] = array(
      'title' => 'Field Export',
      'page callback' => '_slurp_json',
      'access callback' => true,
      'type' => MENU_CALLBACK,
  );
  $items['spit'] = array(
      'title' => 'Field Export',
      'page callback' => '_spit_json',
      'access callback' => true,
      'type' => MENU_CALLBACK,
  );  
  return $items;
}


/*
 * Menu callback for JSON:
 */
function _slurp_json() {
    
  $json = array();
  $json_instances = array();
  $json_field_data = array();

  $entity_type = $_GET['entity'];
  $bundle_name = $_GET['bundle'];

  $fields_info = field_info_instances($entity_type, $bundle_name);
  foreach ($fields_info as $field_name => $value) {
    $instance = field_info_instance($entity_type, $field_name, $bundle_name);
    $field_data = field_info_field($field_name);
    $json_instances[$field_name] = $instance;
    $json_field_data[$field_name] = $field_data;
  }

  $json['fields'] = $json_field_data;
  $json['instances'] = $json_instances;

  header ("Content-Type:application/json");
  
  echo drupal_json_encode($json);

  exit();
  
}


/*
 * Menu callback for JSON:
 */
function _spit_json() {

  drupal_set_time_limit(5*60);

  $entity_type = $_GET['entity'];
  $bundle_name = $_GET['bundle'];
  $enviro = $_GET['enviro'];
  $gettype = $_GET['type'];

  $slurp = _slurp_curl($enviro, $entity_type, $bundle_name);

  $fields = $slurp['fields'];
  $instances = $slurp['instances'];


  //Update Fields:
  if($gettype == 'fields') {
    foreach ($fields as $field_name => $value) {
      echo "<h1>" . $field_name . "</h1>";
      if (isset($fields[$field_name])) {
        $info = field_info_field($field_name);
        if (empty($info)) {
          print "Adding field {$field_name}<br/>\n";
          $field = $fields[$field_name];
          unset($field['id']);
          field_create_field($field);
        }
        else {
          print "Updating field {$field_name}<br/>\n";
          field_update_field($fields[$field_name]);
        }
      }
        /*echo '<pre>';
        print_r($value);
        echo '</pre>';*/
    }
  }
  
  //Update Instances:
  if($gettype == 'instances') {
    foreach ($instances as $field_name => $instance) {
        echo "<h1>" . $field_name . "</h1>";
        if (isset($fields[$field_name])) {
          $info = field_info_instance($entity_type, $field_name, $bundle_name);
          if (empty($info)) {
            print "Adding instance of {$field_name}<br/>\n";
            unset($instance['id']);
            unset($instance['field_id']);
            field_create_instance($instance);
          }
          else {
            print "Updating instance of {$field_name}<br/>\n";
            field_update_field($instance);
          }
          /*echo '<pre>';
          print_r($instance);
          echo '</pre>';*/
        }
    }
  }


  exit();    
}


/**
 * CURL:
 */
function _slurp_curl($enviro = 'qa.takepart.com', $entity, $bundle) {

   $ch = curl_init();   
   $url = "http://" . $enviro . "/slurp?entity=" . urlencode($entity) . "&bundle=" . urlencode($bundle);

   curl_setopt($ch, CURLOPT_URL, $url);
   curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
   $stuff = curl_exec($ch);

   return drupal_json_decode($stuff);
}
