<?php
/**
 * Social Menu
 */

function tp_social_menu_theme(){
  return array(
    'tp_social_menu' => array(
      'variables' => array(
        'elements' => array(),
        'options' => array()
      )
    ),
    'tp_social_menu_menu' => array(
      'variables' => array(
        'items' => array()
      ),
      'template' => 'templates/social-menu'
    ),
  );
}

/**
 * Implements hook_theme()
 * List of possible items->
 * action, social, reach, subscribe, facebook
 */
function theme_tp_social_menu($variables){
  $elements = array();
  foreach($variables['elements'] as $element){
    switch($element){
      case 'action':
//        $elements['takeaction'] = '<p class="takepart-take-action"></p>';
        $elements['takeaction'] = '<h3 class="tp-social-headline takeaction-headline">Take Action</h3><a class="takepart-custom-take-action-button"><i class="tpi icon i-take-action"></i></a>';

        break;
      case 'share':
        $elements['share'] = '<h3 class="tp-social-headline share-headline">Share</h3><div class="share-submenu-wrapper"><div class="share"></div><div class="tp-social"></div><div></div></div>';
        if(isset($variables['options']['comments']) && $variables['options']['comments'] == TRUE){
//          $elements['share'] .= '
//                <p id="article-comments-link" class="comments-link">
//                    <a href="#article-comments">Comments<span class="count"></span></a>
//                </p>';
        }
        break;
      case 'subscribe':
        $subscribe = '<h3 class="tp-social-headline subscribe">Subscribe</h3><div></div>';
        $elements['subscribe'] = l($subscribe, '//go.takepart.com/clients/takepart/survey.htm', array('html' => TRUE, 'attributes' => array('target' => '_blank')));
        break;
      case 'facebook':
        global $base_url;
        $elements['facebook'] = '<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.takepart.com&amp;width&amp;layout=button&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=35" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:35px;" allowTransparency="true"></iframe>';
//        $elements['facebook'] = '<div class="fb-like" data-href="'. $base_url. '" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div>';
        $elements['facebook'] .= '<h3 class="tp-social-headline subscribe">Us</h3>';
        break;
      case 'overlay':
        $elements['overlay'] = '<div class="tap-influence-overlay"></div>';
        break;
    }
  }

  $menu = theme('tp_social_menu_menu', array('items' => $elements));
  return $menu;
}