<?php

/**
 * hook node presave
 * When saving the node re calculate the time to read
 */
function tp_time_to_read_node_presave($node) {
  if (in_array($node->type , array('openpublish_article', 'video', 'video_playlist', 'feature_article', 'fresh_gallery'))) {
    if($read_or = field_get_items('node', $node, 'field_time_to_read_override')) {
      if(!$read_or[0]['value']) {
        $time = _tp_time_to_read_calc($node->body[LANGUAGE_NONE][0]['value']);
        $node->field_time_to_read[LANGUAGE_NONE][0] = array('value' => $time);
        field_attach_update('node', $node);
      }
    }
  }
}

/**
 * hook preprocess node
 * If the time does not exist calculate and save it.
 */
function tp_time_to_read_preprocess_node(&$vars) {
  $node = $vars['node'];
  if (in_array($node->type , array('openpublish_article', 'video', 'video_playlist', 'feature_article', 'fresh_gallery'))) {
    $read_or = field_get_items('node', $node, 'field_time_to_read_override');
    if(empty($read_or) || !$read_or[0]['value']) {
      if(!($time_to_read = field_get_items('node', $node, 'field_time_to_read'))) {
        $time = _tp_time_to_read_calc($node->body[LANGUAGE_NONE][0]['value']);
        $node->field_time_to_read[LANGUAGE_NONE][0] = array('value' => $time);
        node_save($node);
      }
    }
  }
}

/**
 * This function will return the word count
 */
function _tp_time_to_read_calc($value) {
  $wpm = 275;
  $ictime = 8;
  $inline_time = $time = 0;
  $count = str_word_count(strip_tags($value));
  $time = ceil(($count/$wpm)*60);
  $inline_count = substr_count($value, '<hr>');
  $inline_time = $inline_count * $ictime;
  $fulltime = gmdate("H:i:s",($time+$inline_time));
  return $fulltime;
}
