<?php

/**
 * Implements hook_url_inbound_alter().
 */
function takepart_galleries_url_inbound_alter(&$path, $original_path, $path_language) {
  $dirs = explode('/', $path);
  if($dirs[0] == 'photos') {
    $nodeurl = drupal_lookup_path('source', dirname($path));
    $path = $nodeurl;
  }
}

/**
 * Implements hook_init().
 *
 * Commented out by Matt Wrather, 2014-05-28
 */
// function takepart_galleries_init() {
  
//   $first_folder = substr(substr($_SERVER["REQUEST_URI"],1), 0, strpos(substr($_SERVER["REQUEST_URI"],1), "/"));
//   $last_folder = substr(substr($_SERVER["REQUEST_URI"],1), strrpos(substr($_SERVER["REQUEST_URI"],0), "/"), strlen($_SERVER["REQUEST_URI"]));
//   if($first_folder == 'photos') {
//     $js_path = drupal_get_path('module', 'takepart_galleries') . '/js/takepart_galleries.js';
//     drupal_add_css(
//         '.addthis_button_facebook_like:hover{opacity:1 !important;}',
//         array(
//             'group' => CSS_THEME,
//             'type' => 'inline',
//         )
//     );
//     drupal_add_js($js_path);
//     if ( arg(0) == 'node' && is_numeric(arg(1)) ) {
//       $nid = arg(1);
//       _takepart_galleries_metatags($nid);
//       $jsonjs = "var takepart_galleries_json = " . drupal_json_encode(_takepart_galleries_mappings($nid)) . ";";
//       drupal_add_js($jsonjs, array('type' => 'inline', 'scope' => 'header', 'weight' => 0));
//     }
//     $settings['gallery'] = array(
//         'nid' => $nid,
//     );
//     drupal_add_js($settings, 'setting');
//   }
// }

/**
 * Implements hook_entity_update().
 */
function takepart_galleries_entity_update($entity, $type) {

  if($type=='file') {

    if(isset($entity->{'field_page_name'})) {

      $sql = 'SELECT
      file_managed.filename as filename,
      field_data_field_gallery_images.entity_id as entity_id,
      field_data_field_page_name.field_page_name_value as url
      FROM
      {file_managed}
      RIGHT OUTER JOIN field_data_field_gallery_images ON file_managed.fid = field_data_field_gallery_images.field_gallery_images_fid
      LEFT JOIN field_data_field_page_name ON file_managed.fid = field_data_field_page_name.entity_id
      where fid = :fid';
       
      $fid = $entity->field_page_name['fid'];

      $result = db_query($sql, array(':fid' => $fid), array('target' => 'slave'))->fetchAll(PDO::FETCH_ASSOC);

      foreach ($result as $row) {
         
        $links = array(
            'id' => $entity->fid,
            'type' => 'takepart_galleries',
            'loc' => $entity->field_page_name['und'] . '/' . $row['url'],
            'language' => 'und',
            'access' => 1,
            'status' => 1,
            'status_override' => 0,
            'lastmod' => time(),
            'priority' => 0.5,
            'priority_override' => 0,
            'priority_default' => 0.5,
            'changefreq' => 4600,
            'priority' => 0.5,
        );

        xmlsitemap_link_save($links);
      }

    }
  }
}

/**
 * Implementation of hook_menu().
 */
function takepart_galleries_menu() {

  $items = array();

  $items['galleries_json_nid/%'] = array(
      'type' => MENU_CALLBACK,
      'access arguments' => array('access content'),
      'page callback' => '_takepart_galleries_mappings_json',
      'page arguments' => array(1),
  );

  return $items;
}

/**
 * Fixes URLs
 */
function _takepart_galleries_fix_urls(&$item, $key) {
  if(isset($item['title'])) {
    if(!isset($item['url'])) {
      $item['url'] = strtolower(ereg_replace("[^a-zA-Z0-9\s\-]", "", preg_replace("/\s/", "-", $item['title'])));
    }
  }
  if(!isset($item['url'])) {
    if(isset($item['filename'])) {
      $filename = strtok($item['filename'], ".");
      if($filename) {
        $item['url'] = strtolower($filename);
      }
    }
  }
}

/**
 * Similar to above, helper function to get slide's token
 */
function _takepart_galleries_get_token($title, $filename) {
  $token = '';

  if ( $title ) {
    $title = htmlspecialchars_decode($title, ENT_QUOTES);
    $token = strtolower(ereg_replace("[^a-zA-Z0-9\s\-]", "", preg_replace("/\s/", "-", $title)));
  }

  if ( $token == '' && $filename ) {
    $filename = htmlspecialchars_decode($filename, ENT_QUOTES);
    $filename = strtok($filename, ".");
    if($filename) {
      $token = strtolower($filename);
    }
  }

  return $token;
}

/**
 * Return JSON for specified gallery
 */
function _takepart_galleries_mappings_json($nid) {
  return drupal_json_output(_takepart_galleries_mappings($nid));
}

/**
 * Return JSON for specified gallery
 */
function _takepart_galleries_mappings($nid) {

  
  if(!isset($GLOBALS["_takepart_galleries_mappings_return"])) {
  
    if($nid) {
  
      $sql = 'SELECT
    file_managed.uri AS filename,
      field_data_field_gallery_images.entity_id AS entity_id,
      field_data_field_page_name.field_page_name_value AS url,
    field_data_field_image_title.field_image_title_value as title,
    field_data_field_media_caption.field_media_caption_value as caption
      FROM
      {file_managed}
      RIGHT OUTER JOIN field_data_field_gallery_images ON file_managed.fid = field_data_field_gallery_images.field_gallery_images_fid
      LEFT JOIN field_data_field_page_name ON file_managed.fid = field_data_field_page_name.entity_id
    LEFT JOIN field_data_field_media_caption ON file_managed.fid = field_data_field_media_caption.entity_id
      LEFT JOIN field_data_field_image_title ON field_data_field_image_title.entity_id = file_managed.fid
      where field_data_field_gallery_images.entity_id = :nid';
       
      $result = db_query($sql, array(':nid' => $nid), array('target' => 'slave'))->fetchAll(PDO::FETCH_ASSOC);
  
      array_walk($result, '_takepart_galleries_fix_urls');

      $GLOBALS["_takepart_galleries_mappings_return"] = $result;
      return $result;
    }
    
  } else {
       return $GLOBALS["_takepart_galleries_mappings_return"];
  }
}

/**
 * Implements hook_omniture_variables().
 */
function takepart_galleries_omniture_variables() {
  $node = menu_get_object();

  $return = array();
  $folders = explode('/', $_SERVER['REQUEST_URI']);
  $first_folder = $folders[1];
  $second_folder = @$folders[2];
  $third_folder = @$folders[3];
  if ( $first_folder == 'photos' ) {
    $field_display_cover = field_get_items('node', $node, 'field_display_cover');
    $field_display_cover = ( $field_display_cover ) ? $field_display_cover[0]['value'] : false;

    if ( $third_folder == 'next-gallery' ) {
      $return = $return + (array('s.linkTrackEvents'=>'event14,event16','s.events'=>'event14,event16','s.eVar16'=>'Up Next Gallery Cover'));
    } elseif ( $third_folder || (!$field_display_cover && $second_folder) ) {
      $return = $return + (array('s.linkTrackEvents'=>'event14,event15','s.events'=>'event14,event15','s.eVar16'=>'Photo'));
    } elseif ( $second_folder ) {
      $return = $return + (array('s.linkTrackEvents'=>'event14','s.events'=>'event14','s.eVar16'=>'Gallery Cover'));
    }
    return array("variables" => $return);
  }
}

/*
 * Unset duplicate header values and set og:image to match the current slide
 */
function takepart_galleries_html_head_alter(&$head_elements) {

  $path = $_SERVER["REQUEST_URI"];
  $path = preg_replace('/\?.*/', '', $path);
  $dirs = explode('/', $path);
  if(($dirs[1] == 'photos') && (count($dirs) > 3) && $dirs[3] ) {
    foreach ($head_elements as $key => $element) {
      if (isset($element['#id']) &&
          (
		  	  ($element['#id'] == 'metatag_og:url') ||
              ($element['#id'] == 'metatag_og:image') ||
              ($element['#id'] == 'metatag_og:description') ||
              ($element['#id'] == 'metatag_og:title')
          )
       ) {
        unset($head_elements[$key]);
      }
    }
  }
  
	// Update the og:image value if you're on a sub-page
	if($dirs[3]) {
		$node = node_load(arg(1));

		// Ripped off from takepart_gallery_support.module -
		// Get the slideshow, get the slide title, convert it to a url-style string, and check it against arg(2)
		// Then return the updated value to the og:image key in $head_elements
		$slides = field_get_items('node', $node, 'field_gallery_images');
		if ($slides) {
			foreach ($slides as $delta => $item) {
				$file = $item['file'];
				$slide = array();

				$items = field_get_items('file', $file, 'field_image_title');
				$slide['title'] = $items[0]['safe_value'];

				if($slide['title']) {
					$slide['data-token'] = strtolower(preg_replace("[^a-zA-Z0-9\s\-]", "", preg_replace("/\s/", "-", htmlspecialchars_decode($slide['title'], ENT_QUOTES))));
				} else {
					$slide['data-token'] = strtolower(strtok(htmlspecialchars_decode($file->filename, ENT_QUOTES), "."));
				}

				if($slide['data-token'] == $dirs[3]) {
					$head_elements['metatag_og:image_0']['#value'] = file_create_url($file->uri);
					break;
				}
			}
		}
	}
}




/**
 * Implements hook_init().
 */
function _takepart_galleries_metatags($nid) {

  $path = $_SERVER["REQUEST_URI"];
  $path = preg_replace('/\?.*/', '', $path);
  $dirs = explode('/', $path);

  $gallery = _takepart_galleries_mappings($nid);

  $node = node_load($nid);
  $gallery_has_cover = !!$node->field_display_cover[LANGUAGE_NONE][0]['value']; // hacky

  $phototitle = $photocaption = $photopath = null;

  // if we are on a gallery slide, find values for og: tags
  // that match the current gallery slide
  if(($dirs[1] == 'photos') && (count($dirs) > 3)) {
    $last_folder = substr(substr($path,1), strrpos(substr($path,0), "/"), strlen($path));

    for ($i = 0; $i < count($gallery); ++$i) {
      if($last_folder == $gallery[$i]['url']) {
        $phototitle = $gallery[$i]['title'];
        $photocaption = $gallery[$i]['caption'];
        $photopath = file_create_url($gallery[$i]['filename']);
      }
    }

  } else {
    // otherwise...
    // if the gallery has a cover, the metatag module takes care of us
    // but if not, we populate with values from the first slide
    // (We don't default to these above to prevent duplicate og: meta tags)
    if (!$gallery_has_cover) {
      $phototitle = $gallery[0]['title'];
      $photocaption = $gallery[0]['caption'];
      $photopath = file_create_url($gallery[0]['filename']);
    }
  }


  if ($phototitle) {
    //$photopath = url('sites/default/files/'.$photopath, array('absolute'=>true));
 
    $extra_meta_tags = array(
        'takepart_galleries_og_url' => array(
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => array(
                'property' => 'og:url',
                'content' => '//' . $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"]
            ),
        ),
        'takepart_galleries_og_title' => array(
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => array(
                'property' => 'og:title',
                'content' =>  $phototitle
            ),
        ),
        'takepart_galleries_og_caption' => array(
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => array(
                'property' => 'og:description',
                'content' =>  strip_tags($photocaption)
            ),
        ),
        'takepart_galleries_og_image' => array(
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => array(
                'property' => 'og:image',
                'content' => $photopath
            ),
        ),
    );

    foreach($extra_meta_tags as $key=>$metatag) {
      drupal_add_html_head( $metatag, $key);
    }
  }
}
