<?php
// $Id$
/**
 * TakePart Galleries
 * @file
 * @author ctoepfer
 * @date 06/10/2012
 * @company TakePart, LLC
 */

/**
 * Implementation of hook_install().
 */
function takepart_galleries_install() {
  drupal_set_message(st('The TakePart Galleries module has been installed.'));
}

/**
 * Implementation of hook_uninstall().
 */
function takepart_galleries_uninstall() {
  drupal_set_message(st('The TakePart Galleries module has been uninstalled.'));
}
