<?php


/**
 * Implements hook_form_alter().
 */
function takepart_contact_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'webform_client_form_170') {
    // this sets the value for the referring URL field
    $contact_js = <<<EOT
(function ($) {
  Drupal.behaviors.cfSetReferrer = {
    attach: function (context, settings) {
      $('#webform-client-form-170 #edit-submitted-referring-url').val(document.referrer);
    }
  }
})(jQuery);
EOT;

    drupal_add_js($contact_js, 'inline');

    // hide the field
    drupal_add_css("#webform-component-referring-url {display: none; }", 'inline');
  }
}

