<?php
/**
 * @file
 * TakePart module for functions related to the January 2014 redesign
 * of Takepart Galleries
 */

define("TAKEPART_GALLERY_SUPPORT_TEMPLATE_PATH", drupal_get_path('module', 'takepart_gallery_support') . '/templates');

/**
 * Implements hook_help().
 */
function takepart_gallery_support_help($path, $arg) {
  switch ($path) {
    case 'admin/help#takepart_gallery_support':
      return '<p>' . t('Support module for TP galleries.') . '</p>';    
  }
}

/**
 * Implements hook_block_info();
 */
function takepart_gallery_support_block_info() {
  $blocks = array();

  $blocks['takepart_gallery_cover_slide'] = array(
    'info' => t('Takepart Gallery Cover Slide'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view();
 */
function takepart_gallery_support_block_view($delta) {
  $block = array();

  switch ($delta) {
    case 'takepart_gallery_cover_slide':
      $block['content'] = _takepart_gallery_cover_slide();
      break;
  }

  return $block;
}


/**
 * Implements hook_theme().
 */
function takepart_gallery_support_theme() {
  return array(
    'gallery_cover_slide' => array(
      'variables' => array(
        'node' => NULL,
      ),
      'template' => 'gallery-cover-slide',
      'path' => TAKEPART_GALLERY_SUPPORT_TEMPLATE_PATH, 
    ),
  );
}

/**
 * Implements template_preprocess_HOOK().
 *
 * Prepare variables for including in the cover slide template
 */
function template_preprocess_gallery_cover_slide(&$variables) {
  $node = $variables['node'];
  $variables['gallery_title'] = $node->title;

  if ($node->field_gallery_main_image) {
    $cover_slide = field_get_items('node', $node, 'field_gallery_main_image');
  } else {
    $cover_slide = field_get_items('node', $node, 'field_thumbnail');
  }

  $variables['gallery_cover_image'] = theme('image_style', array(
    'path' => $cover_slide[0]['file']->uri,
    'style_name' => 'tp_gallery_slide',
    'alt' => $node->title,
  ));
}

/**
 * Implements hook_preprocess_block().
 *
 * Put a class on the cover slide for theming.
 */
function takepart_gallery_support_preprocess_block(&$variables) {
  if($variables['block']->delta == 'takepart_gallery_cover_slide') {
    $variables['classes_array'][] = 'takepart-gallery-cover-slide';
  }
}

/**
 * Utility function to render out the cover slide.
 */
function _takepart_gallery_cover_slide() {

  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nid = arg(1);
    $node = node_load($nid);
    $show_cover = field_get_items('node', $node, 'field_display_cover');

    if ($show_cover[0]['value']) {
      return theme('gallery_cover_slide', array('node' => $node));
    }
  }
}
