<?php



/**
 * Implements hook_init().
 */
function _takepart_calendar_init() {
  //@todo: only add this w/ content
  //move to formatter_view?
  //media print $css_paths[] = drupal_get_path('module', 'takepart_calendar') . '/fullcalendar/fullcalendar.print.css';
  
  //$css_path = drupal_get_path('module', 'takepart_calendar') . '/themes/cupertino/theme.css';
  //drupal_add_css($css_path);  

  $css_path = drupal_get_path('module', 'takepart_calendar') . '/themes/takepart/theme.css';
  drupal_add_css($css_path);  
  
  $css_path = drupal_get_path('module', 'takepart_calendar') . '/fullcalendar/fullcalendar.css';
  drupal_add_css($css_path);
  
  #@todo: use drupal's jquery:
  $js_path = drupal_get_path('module', 'takepart_calendar') . '/jquery/jquery-1.5.2.min.js';
  drupal_add_js($js_path);
  $js_path = drupal_get_path('module', 'takepart_calendar') . '/jquery/jquery-ui-1.8.11.custom.min.js';
  drupal_add_js($js_path);
  //$js_path = drupal_get_path('module', 'takepart_calendar') . '/fullcalendar/fullcalendar.min.js';
  $js_path = drupal_get_path('module', 'takepart_calendar') . '/fullcalendar/fullcalendar.js';
  drupal_add_js($js_path);


  drupal_add_js("$(document).ready(function() {
      var date = new Date();
      var d = date.getDate();
      var m = date.getMonth();
      var y = date.getFullYear();
	  if(calendar_events) {
        $('#calendar').fullCalendar({
          editable: true,
          events: calendar_events
        });
      }
    });",
  array('type' => 'inline', 'scope' => 'footer', 'weight' => 5)
  );
  
  
  drupal_add_js("jQuery(document).ready(function() {
      		//alert(jQuery('#page').html());
      });",
  array('type' => 'inline', 'scope' => 'footer', 'weight' => 6)
  );


}  

/**
 * Implements hook_field_info().
 */
function takepart_calendar_field_info() {
  return array(
    'takepart_calendar' => array(
      'label' => t('TakePart Calendar'),
      'description' => t('Managable Calendar'),
      'default_widget' => 'takepart_calendar_widget',
      'default_formatter' => 'takepart_calendar_formatter',
  ),
  );
}



/**
 * Implements hook_field_formatter_info().
 */
function takepart_calendar_field_formatter_info() {
  return array(
'takepart_calendar_formatter' => array(
'label' => t('Test TakePart calendar formatter'),
          'field types' => array('takepart_calendar'),
  ),
  );
}


/**
* Implements hook_field_formatter_view().
*/
function takepart_calendar_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  
  _takepart_calendar_init();
  
  $element = array();

  switch ($display['type']) {
    case 'takepart_calendar_formatter':
      foreach ($items as $delta => $item) {
        if ($item['takepart_calendar']) {
          $json = $item['takepart_calendar'];
          //@todo: turn this into an ajax feed:
          $element[$delta]['#markup'] = '<span><script type=\'text/javascript\'>var calendar_events = ' . $json .';</script><div id=\'calendar\'></div></span>';
        }
      }
      break;
  }
  return $element;
}




/**
* Implements hook_field_widget_form().
*/
function takepart_calendar_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $field_name = $field['field_name'];
  $field_type = $field['type'];

  $default = $instance['default_value'][0][$field_type][$field_type];

  //@todo: check delta for null offset?
  
  switch ($instance['widget']['type']) {
    case 'takepart_calendar':

      $element['takepart_calendar'] = array(
          '#type' => 'textarea',
          '#title' => $element['#title'],
          '#description' => $element['#description'],
          '#default_value' => $items[$delta]['takepart_calendar'],
          '#required' => $element['#required'],
          '#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
          '#delta' => $delta,
          '#element_validate' => array('_takepart_calendar_validation'),
      );

      $element['takepart_calendar_html'] = array(
        '#type' => 'markup',
        '#value' => t('TEST MARKUP'),
      );
      
      
    /*  
     * 
      drupal_add_js("jQuery('test');",
        array('type' => 'inline', 'scope' => 'footer', 'weight' => 6)
      );
      */
      
      /*
      drupal_add_js("jQuery(document).ready(function() {
      				alert('ready');
            		//alert(jQuery('#edit-field-cal-test-und-0-takepart-calendar').attr('id'));
            });",
      array('type' => 'inline', 'scope' => 'footer', 'weight' => 6)
      );
      */
      
      break;
  }
  return $element;
}


/**
* Implements hook_field_widget_error().
*/
function takepart_calendar_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'takepart_calendar_invalid':
      form_error($element, $error['message']);
      break;
  }
}


/**
 * Implements hook_field_is_empty().
 */
function takepart_calendar_field_is_empty($item, $field) {
  if (empty($item['takepart_calendar'])) {
    return true;
  }
}

/**
 * Implements hook_field_widget_info().
 */
function takepart_calendar_field_widget_info() {
  return array(
    'takepart_calendar' => array(
      'label' => t('TakePart Calendar'),
      'field types' => array('takepart_calendar'),
  ),
  );
}


function _takepart_calendar_validation($element, &$form_state) {
  if (isset($element['#value'])) {
     //form_set_value($element, array('takepart_calendar' => $value), $form_state);
  }
}



/* For futue implementation, blocks:
 function takepart_calendar_block_info() {
$blocks = array();

$blocks['info'] = array(
'info' => t('TakePart Calendar Block')
);

return $blocks;
}

function takepart_calendar_block_view($delta = ''){
$block = array();

$block['subject'] = "TPC Subject";
$block['content'] = "TakePart Calendar Content";

return $block;
}
*/