<?php
/**
 * @file
 * Participant Media Core.
 */

/**
 * Implements hook_boot().
 */
function pm_core_boot() {
  // Load the Composer autoloader.
  require_once __DIR__ . '/vendor/autoload.php';
  // Initialize the Doctrine Entity Manager.
  \Participant\App::init(array(
    'development_mode' => ENVIRONMENT == 'development' || ENVIRONMENT == 'test',
    'entity_path' => __DIR__ . '/app/src',
    'db_user' => DATABASE_USER,
    'db_pass' => DATABASE_PASS,
    'db_name' => DATABASE_NAME,
    'db_host' => DATABASE_HOST,
  ));
}

/**
 * Implements hook_help().
 */
function pm_core_help($path, $arg) {
  $output = '';
  if ($path == 'admin/help#pm_core') {
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t("The Participant Media Core module provides common utilities and classes for other custom modules.") . '</p>';
  }
  return $output;
}

/**
 * Implements hook_menu().
 */
function pm_core_menu() {
  return array(
    'admin/config/customization' => array(
      'title' => 'Customization',
      'description' => 'Configuration of custom modules',
      'position' => 'right',
      'weight' => 0,
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
    ),
  );
}

/* Helper and utility functions
 ******************************************************************************/

/**
 * Split a string into an array of strings.
 *
 * This function splits a single string value into an array of string values
 * given one or more delimiters. Additionally, consecutive delimiters are
 * collapsed into a single delimiter, and each split piece is trimmed of
 * whitespace.
 *
 * @param string $value
 *   The string to split
 * @param string $delimiters
 *   The delimiter
 * @param array $alternates
 *   An array of additional delimiter strings. These delimiters are replaced
 *   with the primary delimiter (using str_replace) before exploding the value.
 *
 * @return array
 *   Array of trimmed strings created from splitting $value.
 */
function pm_split($value, $delimiter, $alternates = array()) {
  if (count($alternates) > 0) {
    // Replace all alternate delimiters with the primary delimter.
    $value = str_replace($alternates, $delimiter, $value);
  }
  $list = explode($delimiter, $value);
  $trimmed = array_map('trim', $list);
  return array_filter($trimmed, 'strlen');
}

/**
 * URL form element validation callback.
 */
function pm_core_element_validate_url($element, &$form_state) {
  if (!empty($element['#value'])) {
    if (!valid_url($element['#value'], TRUE)) {
      form_error($element, t('@title must be an absolute URL.', array(
        '@title' => $element['#title'],
      )));
    }
  }
}
