<?php
/**
 * @file
 * Code for the TakePart Search feature.
 */

include_once('takepart_search.features.inc');

function takepart_search_form_search_api_page_search_form_1_alter(&$form, &$form_state, $form_id) {
  $form['keys_1']['#default_value'] = 'Search TakePart';
  $form['keys_1']['#attributes'] = array('onfocus' => array("if(this.value=='" . t('Search TakePart') . "'){this.value=''};"));
  $form['submit_1']['#attributes'] = array('class' => array('tpform-submit'));
}
