<?php

function tp_theme_support_menu() {
	
	$items = array();

    $items['admin/config/fresh'] = array(
		'title' => "Fresh Theme Support",
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('access administration pages'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
		'weight' => -18,
    );

    $items['admin/config/fresh/footer'] = array(
		'title' => 'Footer',
		'description' => 'About Us text block for footer',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tp_theme_support_footer_form'),
		'access callback' => 'user_access',
		'access arguments' => array('tp_theme_support configure settings'),
		'file' => 'tp_theme_support.forms.inc',
    );
	
	return $items;
}

/**
 * Implements hook_permission().
 */
function tp_theme_support_permission() {
	return array(
		'tp_theme_support configure settings' => array(
		'title' => t('Configure global settings'),
		'description' => t("Configure global settings for 'Fresh' theme."),
		'restrict access' => TRUE,
		),
	);
}

function tp_theme_support_library_alter(&$javascript, $module) {
  // Replace jQuery Form plugin.
  $javascript['jquery.form']['js']['misc/jquery.form.js']['data'] = 'sites/all/modules/contrib/jquery_update/replace/misc/jquery.form.min.js';
  $javascript['jquery.form']['version'] = '2.69';
}