<?php
module_load_include("inc", 'alt_media_widget', 'includes/media.fields');
module_load_include("inc", "media", "includes/media.pages");
drupal_add_js(drupal_get_path('module', 'alt_media_widget') ."/alt_media_widget.js");
drupal_add_css(drupal_get_path('module', 'alt_media_widget') ."/alt_media_widget.css");


function alt_media_widget_menu() {
  $menu['media/amw/%/%/%/%file'] = array(
    'title' => 'ajax',
    'page callback' => 'alt_media_widget_dialog_callback',
    'page arguments' => array(5,2,3,4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $menu;
}

function alt_media_widget_dialog_callback($file, $action, $field, $delta) {
  switch($action) {
    case 'edit':
      $file->dialog_inner = "media-dialog-inner-$field-$delta";
      $form = drupal_get_form('media_edit', $file);
    break;
    case 'select':
      $form = drupal_get_form('alt_media_widget_amw_media_select');
  }
  $form['#prefix'] = "<div class = 'media-edit-wrapper' id = 'media-dialog-inner-$field-$delta'>";
  $form['#suffix'] = "</div>";
  //return $form;
  $cmds['#commands'][] = ajax_command_insert(NULL, drupal_render($form));
  $cmds['#commands'][] = ajax_command_invoke("#media-dialog-inner-$field-$delta", 'trigger', array('open'));
  $cmds['#type'] = 'ajax';
  ajax_deliver($cmds);
  
}

function alt_media_widget_form_media_edit_alter(&$form, $form_state) {
  $file = $form_state['file'];
  $form['actions']['submit']['#ajax'] = array(
     'callback' => 'alt_media_widget_dialog_submit_callback',
     'wrapper' => $form['#dialog-inner'],
     'name' => 'sumbit2',
  );
  $form['actions']['save'] = $form['actions']['submit'];
 unset($form['actions']['submit']);
 unset($form['actions']['delete']);
}
function alt_media_widget_dialog_submit_callback($form, $form_state) {
  $file = $form_state['file'];
    $cmds['#commands'][] = ajax_command_insert(NULL, drupal_render($form));
    $cmds['#commands'][] = ajax_command_alert($file->dialog_inner ."bpb");
    $cmds['#commands'][] = ajax_command_invoke('#' . $file->dialog_inner, "trigger", array('close'));
    $cmds['#type'] = 'ajax';
  return $cmds;
}


function alt_media_widget_amw_callback($form, $form_state) {
  //dpm($form_state);
  $parents = $form_state['triggering_element']['#array_parents'];
  array_pop($parents);
  return drupal_array_get_nested_value($form, $parents);
  return print_r($form_state['triggering_element'], TRUE);
  return print_r(array_keys($form_state), TRUE);
}
