<?php

/**
 * Implements hook_field_info().
 */
function gmapfield_field_info() {
  return array(
    'gmapfield' => array(
      'label' => t('Google Maps Field'),
      'fieldable' => TRUE,	   
      'description' => t('A field composed of an address.'),
      'default_widget' => 'gmapfield_widget',
      'default_formatter' => 'gmapfield_formatter',
    ),
  );
}


/**
 * Implements hook_field_widget_info().
 */
function gmapfield_field_widget_info() {
  return array(
    'gmapfield_formatter' => array(
      'label' => t('Google Map Field'),
      'field types' => array('gmapfield'),
      'settings' => array(),
    ),
  );
}


/**
 * Implements hook_field_is_empty().
 */
function gmapfield_field_is_empty($item, $field) {
  if (!isset($item['gmapfield_address']) || $item['gmapfield_address'] === '') {
    return TRUE;
  }
  return FALSE;
}


/**
 * Implements hook_field_formatter_info().
 */
function gmapfield_field_formatter_info() {
  return array(
    'gmapfield_formatter' => array(
      'label' => t('Google map display'),
      'field types' => array('gmapfield'),
    ),
  );
}




/**
 * Implements hook_field_formatter_view().
 */
function gmapfield_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  drupal_add_css(drupal_get_path('module', 'gmapfield') . '/gmapfield_field_view.css', array('group' => CSS_DEFAULT, 'type' => 'file'));

  $element = array();

  $jsoutput = '';

  switch ($display['type']) {
    case 'gmapfield_formatter':

	  foreach ($items as $delta => $item) {

	    $jsoutput .= "addresses[$delta]=['" . $item['gmapfield_address'] . "', image, shadow, '" . str_replace("'","\\'", $item['gmapfield_popup']) . "'];";

            if(end($items) === $item) {
		drupal_add_js(_gmapfield_getjs($jsoutput, 'map_canvas'.$delta), array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
		//drupal_add_js(_gmapfield_getjs($jsoutput, 'page'), array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
                $output = ('<div class="map_canvas" id="map_canvas'.$delta.'"></div>');
	    } else {
		$output = ('<div class="map_canvas_inactive" id="map_canvas'.$delta.'"></div>');
	    	
	    }
	 
	    $element[$delta] = array('#markup' => $output);

	  }

      break;
  }

  return $element;
}


/**
 * Implements hook_field_widget_form().
 */
function gmapfield_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
	$element += array(
	    '#type' => 'fieldset',
	    '#delta' => $delta,
	    '#attached' => array(
	      'css' => array(drupal_get_path('module', 'gmapfield') . '/gmapfield_fieldset.css'),
	    ),
	    'gmapfield_address' => array(
		'#title' => t('Address'),
		'#type' => 'textfield',
		'#default_value' => isset($items[$delta]['gmapfield_address']) ? $items[$delta]['gmapfield_address'] : '',
		'#attributes' => array('class' => array('visits-entry', 'visits-year')),
		'#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
		'#element_validate' => array('gmapfield_validation'),
	    ),
	    'gmapfield_popup' => array(
		'#type' => 'textarea',
		'#title' => t('Popup'),
		'#description' => $element['#description'],
		'#default_value' => isset($items[$delta]['gmapfield_popup']) ? $items[$delta]['gmapfield_popup'] : '',
		'#required' => $element['#required'],
		'#weight' => isset($element['#weight']) ? $element['#weight'] : 1,
		'#element_validate' => array('gmapfield_validation'),
	    ),
	  );
	  return $element;
}

/**
 * Validation hook.
 */
function gmapfield_validation($element, &$form_state) {
  if (isset($element['#value'])) {
	//@todo: validation code
  }
}


/**
 * Implements hook_field_widget_error().
 */
function gmapfield_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'gmapfield_invalid':
      form_error($element, $error['message']);
      break;
  }
}


function _gmapfield_getjs($addresses, $divid) {
//@todo: move some of this into a js file
       $content = <<<HTM
var tpmaps = tpmaps || {};

tpmaps.initialize = function() {

       //alert('ok');

       geocoder = new google.maps.Geocoder();
        
        var $ = jQuery;

        var image = new google.maps.MarkerImage('http://maps.google.com/mapfiles/marker_green.png',
            // This marker is 20 pixels wide by 32 pixels tall.
            new google.maps.Size(20, 34),
            // The origin for this image is 0,0.
            new google.maps.Point(0,0),
            // The anchor for this image is the base of the flagpole at 0,32.
            new google.maps.Point(0, 32));


        var shadow = new google.maps.MarkerImage('http://maps.google.com/mapfiles/shadow50.png',

            new google.maps.Size(37, 34),
            new google.maps.Point(0,0),
            new google.maps.Point(0,34));
    
        var addresses=new Array();

	$addresses

        tpmaps.builtfirst = false;

        for (var i_addr=0;i_addr<addresses.length;i_addr++) {  

            tpmaps.html = addresses[i_addr][3];

            geocoder.geocode( { 'address': addresses[i_addr][0]}, function(results, status) {

                //Position map on first element:

                if(tpmaps.builtfirst == false) { 

		     tpmaps.builtfirst = true;

		     tpmaps.mapcenter = results[0].geometry.location;

                     var mapOptions = {
                            center:  tpmaps.mapcenter,
                            zoom: 12,
                            mapTypeId: google.maps.MapTypeId.ROADMAP
                      };
                  
                      tpmaps.map = new google.maps.Map($('#$divid').get(0), mapOptions);

 	              google.maps.event.addListenerOnce(tpmaps.map, 'idle', function() {
			    //alert('test 2');
			    google.maps.event.trigger(tpmaps.map, 'resize');
			    tpmaps.map.setCenter(tpmaps.mapcenter); // be sure to reset the map center as well
	              });
	
                }

                if (status == google.maps.GeocoderStatus.OK) {
                    //tpmaps.map.setCenter(results[0].geometry.location);
                    //addresses[i].push(results[0].geometry.location);

                    var shape = {
                        coord: [0, 0, 64, 0, 64, 64, 0, 64],
                        type: 'poly'
                    };

                    var marker = new google.maps.Marker({
                            map: tpmaps.map,
                            position: results[0].geometry.location,
                            shadow: shadow,
                                icon: image,
                                shape: shape
                    });

                    google.maps.event.addListener(marker, 'click', function() {
                            var html_popup = tpmaps.html;

                            var infowindow = new google.maps.InfoWindow(
                                    { content: html_popup,
                                      size: new google.maps.Size(50,50)
                                    });
                            infowindow.open(tpmaps.map,marker);
                        tpmaps.map.setCenter(marker.getPosition());

                    });

                    
		    //alert('geocode passed');

                 } else {
                            //alert("Geocode was not successful for the following reason: " + status);
                            //addresses.splice(i,1);
                 }
            });
        }
}


tpmaps.loadScript = function() {

    var key = 'AIzaSyCBqxSOBaiVARRKgOlOWIRm2lbhBeskn10';
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = 'http://maps.googleapis.com/maps/api/js?key=' + key + '&sensor=false&' +
        'callback=tpmaps.initialize';
    document.body.appendChild(script);
}

tpmaps.waitforcontainer = function() {
    //@todo: add other conditions:
    if((jQuery('#$divid').length > 0) && (jQuery('#$divid').offset().top > 0) && (jQuery('#$divid').offset().left > 0)) {
      //alert('all clear');
      tpmaps.loadScript();
    } else {
      setTimeout(function() {
        tpmaps.waitforcontainer();
      }, 500)
    }
}


tpmaps.waitforcontainer();

HTM;

return $content;
}


