<?php
/**
 * @file
 * Code for the TakePart Gallery feature.
 */

include_once('takepart_gallery.features.inc');


/*
 * Implementation of hook_form_alter to hide certain default phase2_profile fields
 */

function takepart_gallery_form_alter(&$form, &$form_state, $form_id){
  // change gallery title label to "headline" from "title"
  if ($form_id == 'openpublish_photo_gallery_node_form') {
    $form['title']['#title'] = t('Headline');
  }
}