<?php

/**
 * @file
 * Main file for the TakePart Contact Us custom module.
 */

/**
 * Implement hook_form_FORM_ID_alter
 *
 */
function takepart_contact_us_form_zendesk_forms_support_form_alter(&$form, &$form_state, $form_id) {
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name'),
        '#required' => TRUE,
        '#weight' => -10
    );
    $form['requester'] = array(
        '#type' => 'textfield',
        '#title' => t('Email'),
        '#required' => TRUE,
        '#weight' => -9
    );
    $form['file'] = array(
      '#type' => 'file',
      '#title' => t('Please Attach Your Screenshot'),
      '#description' => t('Allowed extensions: jpg, jpeg, png. Max Size: 2MB
        <div class="contact-screenshot-desc">Please help us troubleshoot the issue by including a URL of the page in your message. Here\'s how to <a href="http://www.take-a-screenshot.org" target="_blank">take a screenshot</a>.</div>
        <div class="filesizewarn form-required">Warning your file is too big.</div>'),
      '#weight' => -8,
    );
    $form['zendesk_24199483'] = array(
        '#type' => 'select',
        '#title' => t('Topic'),
        '#options' => array(
          'Story question or comment' => 'Story question or comment',
          'Email subscription' => 'Email subscription',
          'Technical problem' => 'Technical problem',
          'Films' => 'Films',
          'Pivot' => 'Pivot',
          'Privacy' => 'Privacy',
          'Other' => 'Other'
        ),
        '#required' => TRUE,
        '#weight' => -8
    );
    $form['subject'] = array(
        '#type' => 'textfield',
        '#title' => t('Subject'),
        '#required' => TRUE,
        '#maxlength' => 150,
        '#weight' => -7
    );
    $form['description'] = array(
        '#type' => 'textarea',
        '#title' => t('Message'),
        '#required' => TRUE,
        '#maxlength' => 1500,
        '#maxlength_js' => TRUE,
        '#weight' => -6
    );
    $form['group_id'] = array(
        '#type' => 'hidden',
        '#value' => 20740327,
    );
    $form['zendesk_23560737'] = array(
        '#type' => 'hidden',
        '#default_value' => '',
    );
    $form['zendesk_23560727'] = array(
        '#type' => 'hidden',
        '#default_value' => '',
    );
    $form['zendesk_23643146'] = array(
        '#type' => 'hidden',
        '#value' => variable_get('site_name', ''),
    );
    $form['#validate'][0] = 'takepart_contact_us_form_validate';
    $form['#submit'][0] = 'takepart_contact_us_form_submit';
    return $form;
}

/*
 * Need to turn off block caching or else the character limit javascript won't work
 */

function takepart_contact_us_block_info_alter(&$blocks, $theme, $code_blocks) {
    $blocks['zendesk_forms']['zendesk_support_form']['cache'] = DRUPAL_NO_CACHE;
}

/*
 * Alter the block to add the javascript to capture the user's browser information
 * and clear the subject field.
 * zendesk_23560737 (browser)
 * zendesk_23560727 (referrer)
 */

function takepart_contact_us_block_view_zendesk_forms_zendesk_support_form_alter(&$data, $block) {
    $form_body = drupal_get_form('zendesk_forms_support_form');
    $js = '<script type="text/javascript">
        jQuery(document).ready(function() {
          jQuery("input[name=zendesk_23560727]").val(document.referrer);
          jQuery("input[name=zendesk_23560737]").val(navigator.userAgent);
          jQuery(\'#edit-zendesk-24199483--2\').on(\'change\', function() {
            contactFileShow(jQuery(this).val());
          });
          jQuery("#edit-file--2").on("change", function (e) {
            var files = e.currentTarget.files;
            // call them as such files[0].size will get you the file size of the 0th file
            for (var x in files) {
              var filesize = ((files[x].size/1024)/1024).toFixed(4); // MB
              if (files[x].name != "item" && typeof files[x].name != "undefined" && filesize <= 2) {
                jQuery(".filesizewarn").hide();
              } else {
                if(filesize > 2) jQuery(".filesizewarn").show();
              }
            }
          });
          contactFileShow(jQuery(\'#edit-zendesk-24199483--2\').val());
        });
        function contactFileShow(val){
          if(val == \'Technical problem\') {
            jQuery(\'.form-item-files-file\').show();
          } else {
            jQuery(\'.form-item-files-file\').hide();
          }
        }
        </script>';
    $data['subject'] = t('');
    $data['content'] = drupal_render($form_body) . "\n" . $js;
}

/**
 * hook_form_validate
 * Check if the file is the correct format
 */
function takepart_contact_us_form_validate($form, &$form_state) {
  if($form_state['values']['zendesk_24199483'] == 'Technical problem') {

    $file = file_save_upload('file', array(
      // Validates file is really an image.
      'file_validate_is_image' => array(),
      // Validate extensions.
      'file_validate_extensions' => array('png jpg jpeg'),
      // Validate Size
      'file_validate_size' => array('2097152'),
    ));
    // If the file passed validation:
    if ($file) {
      $ext = pathinfo($file->origname, PATHINFO_EXTENSION);
      // Move the file into the Drupal file system.
      if ($file = file_move($file, 'public://'.uniqid(time()).'.'.$ext)) {
        // Save the file for use in the submit handler.
        $form_state['storage']['file'] = $file;
      }
      else {
        form_set_error('file', t("Failed to write the uploaded file to the site's file folder."));
      }
    } else {
      //Need to check if a file was actually attempted and fail validate if it was.
      if(isset($_FILES['files']['name']['file']) && !empty($_FILES['files']['name']['file'])) {
        form_set_error('file', '');
      }
    }
  }
  if(!valid_email_address($form_state['values']['requester'])){
    form_set_error('requester', t("Please enter a valid email address."));
  }
}

/*
 * New submit handler for processing custom fields and group ID field
 */

function takepart_contact_us_form_submit($form, &$form_state) {
    $values = $form_state['values'];
    $ticket = array(
      'description' => $values['description'],
      'requester' => array(
        'name' => $values['name'],
        'email' => $values['requester'],
      ),
      'group_id' => $values['group_id'],
    );
    if (!empty($values['subject'])) {
      $ticket['subject'] = $values['subject'];
    }

    //Handle the file screenshot
    if($values['zendesk_24199483'] == 'Technical problem') {
      if(isset($form_state['storage']['file']) && !empty($form_state['storage']['file'])) {
        $file = $form_state['storage']['file'];
        // We are done with the file, remove it from storage.
        unset($form_state['storage']['file']);
        // Make the storage of the file permanent.
        $file->status = FILE_STATUS_PERMANENT;
        // Save file status.
        file_save($file);

        $ticket['description'] = $ticket['description']."

        SCREENSHOT FROM USER: ".file_create_url($file->uri);
      }
    }

    // Get extra fields that are prefixed with zendesk_. Right now the only way
    // to add extra fields is by using form alter though.
    $extra_fields = array_filter(array_keys($values), create_function('$item', 'return strpos($item, "zendesk_") === 0;'));
    if (!empty($extra_fields)) {
        $ticket['custom_fields'] = array();
        $i = 0;
        foreach ($extra_fields as $field_name) {
            $ticket['custom_fields'][$i]['id'] = intval(substr($field_name, 8));
            $ticket['custom_fields'][$i]['value'] = $values[$field_name];
            $i++;
        }
    }

    // Wrap the ticket array in yet another array and call the API.
    $response = zendesk_forms_api_call(array('ticket' => $ticket), 'tickets.json');
    if (!isset($response->error)) {
        $form_state['redirect'] = 'contact-us/thank-you';
    } else {
        drupal_set_message(t('An error happened while sending the message.'), 'error');
    }
}
