<?php
/**
 * @file
 */
include_once('takepart_custom.features.inc');
include_once('takepart_custom.embeddable.inc');
include_once('takepart_custom.block.inc');
// Drupal needs this blank file.
//
/**
 * Implements hook_form_alter().
 */
 
function takepart_custom_form_node_form_alter(&$form, $form_state, $form_id) {
    // Add access to the 'Publishing options' fieldset.
    $form['options']['promote']['#access'] = FALSE;
    $form['options']['sticky']['#access'] = FALSE;
    $form['revision_information']['revision']['#default_value'] = 1;
    $form['revision_information']['revision']['#access'] = FALSE;
}

