<?php

/**
 * Implements hook_form_FORM_ID_alter()
 */
function waterbillofrights_form_water_bill_of_rights_signature_form_alter(&$form, &$form_state) {

  $module_path = drupal_get_path('module', 'waterbillofrights');
  $path = implode('/', array($module_path, 'css', 'form.css'));
  drupal_add_css($path, array('group' => CSS_DEFAULT, 'type' => 'file'));

  $ngo_title = '';
  if (! empty($form['field_wbor_source_ngo'])) {
    // update the NGO opt-in checkbox to reflect the source NGO.
    $language = $form['field_wbor_source_ngo']['#language'];
    if (! empty($form['field_wbor_source_ngo'][$language][0]['#default_value'])) {
      $ngo_token = $form['field_wbor_source_ngo'][$language][0]['#default_value'];
      // get the NGO name from the list of allowed values
      $field = $form_state['field']['field_wbor_source_ngo'][$language]['field'];
      $ngo_title = isset($field['settings']['allowed_values'][$ngo_token]) ?
        $field['settings']['allowed_values'][$ngo_token] : '';
    }
  }
  if (! empty($form['field_wbor_ngo_opt_in'])) {
    if (! empty($ngo_title)) {
      // update the label for the NGO opt-in checkbox
      $language = $form['field_wbor_ngo_opt_in']['#language'];
      $title = $form['field_wbor_ngo_opt_in'][$language]['#title'];
      if (strpos($title, '@ngo') !== FALSE) {
        $title = t($title, array('@ngo' => $ngo_title));
        $form['field_wbor_ngo_opt_in'][$language]['#title'] = $title;
      }
    }
    else {
      // no NGO, so hide the NGO opt-in checkbox
      $form['field_wbor_ngo_opt_in']['#access'] = FALSE;
    }
  }

  if (! empty($form['signature_email'])) {
    $language = $form['signature_email']['#language'];
    if (! isset($form['signature_email'][$language][0]['#element_validate'])) {
      $form['signature_email'][$language][0]['#element_validate'] = array();
    }
    $form['signature_email'][$language][0]['#element_validate'] += array(
      'waterbillofrights_email_validate'
    );
  }

  $note  = '<div>';
  $note .= '<div class="wbor-zip-code-note">';
  $note .= 'By entering your complete zip code, we can also send the Bill of Rights to your representatives in the House.';
  $note .= '</div>';
  $note .= '<div class="wbor-required-note">';
  $note .= '<span class="form-required">*</span> Required Field';
  $note .= '</div>';
  $note .= '</div>';
  $form['field_wbor_zip_code']['#suffix'] = $note;
}

function waterbillofrights_email_validate($element, &$form_state) {
  $mail = $element['value']['#value'];
  if (!empty($mail) && !valid_email_address($mail)) {
    form_error($element, t('Invalid e-mail address.'));
  }
}
