<?php
$databases = array (
  'default' =>
    array (
      'default' =>
        array (
          'database' => 'takepart',
          'username' => 'root',
          'password' => 'root',
          'host' => 'localhost',
          'port' => '',
          'driver' => 'mysql',
          'prefix' => '',
        ),
    ),
);
$conf['omniture_account_name'] = 'takeparttakepartdev2';
ini_set('error_reporting', !E_NOTICE & !E_WARNING);
ini_set('memory_limit','512M');